=== isc-rsingh/pipeclient/data/schema/task.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://intersystems.com/schemas/task",
    "title": "Task",
    "description": "A data processing job",
    "type": "object",
    "properties": {
        "taskid": {
            "description": "The unique identifier for a task",
            "type": "string"
        },
        "pipelineids": {
            "description": "IDs of all pipelines that contain this task",
            "type": "array", 
            "items": {
                "type": "string"
            }
        },
        "type": {
            "description": "The type of task (e.g. 'table, recipe, AWS RDS ingest, aggregate, join, etc.')",
            "type": "string"
        },
        "source": {
            "description": "The source data for the task",
            "type": "object",
            "properties": {
                "type": {
                    "description": "The type of data source (internal means IRIS)",
                    "type": "string"
                },
                "tasks": {
                    "description": "The tasks that this task depends upon, identified by their unique identifier",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["type"]
        },
        "compute": {
            "description": "Description of the computation this task will do",
            "type": "object",
            "properties": {
                "template": {
                    "description": "Signals this computation uses a structured format which is good for UIs",
                    "type": "object"
                }
            }
        },
        "sink": {
            "description": "The output data set for the task",
            "type": "object",
            "properties": {
                "type": {
                    "description": "The type of data sink (internal means IRIS)",
                    "type": "string"
                },
                "name": {
                    "description": "The (view or table) name of the data sink. In the case of a recipe, the task ID that represents the recipe's final output",
                    "type": "string"
                },
                "properties": {
                    "description": "Field names of the data sink",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "namespace": {
                    "description": "The namespace of the data sink",
                    "type": "string"
                }
            },
            "required": ["type", "name"]
        },
        "metadata": {
            "description": "Useful information for a catalog",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the task",
                    "type": "string"
                },
                "description": {
                    "description": "Description of the task",
                    "type": "string"
                },
                "autodescription": {
                    "description": "Description of the task as generated by code",
                    "type": "string"
                }, 
                "creator": {
                    "description": "User who created the task",
                    "type": "string"
                },
                "created": {
                    "description": "Date and time the task was created",
                    "type": "string"
                },
                "modified": {
                    "description": "Date and time the task was last updated",
                    "type": "string"
                }, 
                "lastrun": {
                    "description": "Date and time the task was last run",
                    "type": "string"
                },
                "publish": {
                    "description": "Whether this task should appear in the catalog",
                    "type": "boolean"
                },
                "required": ["name", "creator", "created"]
            }
        }
    },
    "required": ["taskid", "type", "source", "sink", "metadata"]
}

=== isc-rsingh/pipeclient/data/samples/tasks/0_task-loandata.json
{
    "taskid": "85D0E4D0-ED27-11EC-8DAE-F4D488652FDC-AAAAB",
    "pipelineids": [
        "A1E30B30-EDA9-11EC-8EF4-F4D488652FDC"
    ],
    "source": {
        "type": "internal"
    },
    "type": "rs.pipeline.TaskPersistent",
    "compute": {},
    "sink": {
        "type": "iris|table",
        "name": "RSPIPELINE.XYZ",
        "namespace": "USER"
    },
    "metadata": {
        "creator": "rsingh",
        "publish": false,
        "modified": "66340,69185.808722",
        "name": "Unnamed task",
        "properties": [
            {
                "name": "Loan_ID",
                "type": "VARCHAR"
            },
            {
                "name": "Gender",
                "type": "VARCHAR"
            },
            {
                "name": "Married",
                "type": "VARCHAR"
            },
            {
                "name": "Dependents",
                "type": "INTEGER"
            },
            {
                "name": "Education",
                "type": "VARCHAR"
            },
            {
                "name": "Self_Employed",
                "type": "VARCHAR"
            },
            {
                "name": "ApplicantIncome",
                "type": "INTEGER"
            },
            {
                "name": "CoapplicantIncome",
                "type": "INTEGER"
            },
            {
                "name": "LoanAmount",
                "type": "INTEGER"
            },
            {
                "name": "Loan_Amount_Term",
                "type": "INTEGER"
            },
            {
                "name": "Credit_History",
                "type": "INTEGER"
            },
            {
                "name": "Property_Area",
                "type": "VARCHAR"
            },
            {
                "name": "Loan_Status",
                "type": "VARCHAR"
            }
        ],
        "rowcount": 1740
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/pl3-loans-drop-rows-not-urban.json
{
    "taskid": "loans-drop-rows-not-urban",
    "pipelineids": ["pl3"],
    "type": "rs.pipeline.TaskFilter",
    "source": {
        "type": "internal",
        "tasks": ["loans-drop-rows-loanamount-null"]
    },
    "compute": {
        "template": {
            "outputfields": [],
            "filter": "property_area NOT LIKE 'Urban'"
        }
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.ldrnu",
        "namespace": "USER"
    },
    "metadata": {
        "name": "nonulla",
        "namespace": "USER",
        "description": "nonulla",
        "tags": ["nonulla"]
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/4_task-filter1.json
{
    "taskid": "tf1",
    "pipelineids": ["ppp1"],
    "type": "rs.pipeline.TaskFilter",
    "source": {
        "type": "internal",
        "tasks": ["85D0E4D0-ED27-11EC-8DAE-F4D488652FDC"], 
        "85D0E4D0-ED27-11EC-8DAE-F4D488652FDC": {
            "fields": ["Loan_ID","Gender","Married","Dependents","Education","Self_Employed","ApplicantIncome","CoapplicantIncome","LoanAmount","Loan_Amount_Term","Credit_History","Property_Area","Loan_Status"]
        }
    },
    "compute": {
        "template": {
            "outputfields": ["Loan_ID","Gender","Married","Dependents","Education","Self_Employed"]
        }
    },
    "sink": {
        "type": "iris|view",
        "name": "RSPIPELINE.tf1",
        "namespace": "USER"
    },
    "metadata": {
        "name": "nonulla",
        "namespace": "USER",
        "description": "nonulla",
        "tags": ["nonulla"]
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/pl3-loans-drop-rows-loanamount-null.json
{
    "taskid": "loans-drop-rows-loanamount-null",
    "pipelineids": ["pl3"],
    "type": "rs.pipeline.TaskFilter",
    "source": {
        "type": "internal",
        "tasks": ["loans-drop-selfemp-married-gender"]
    },
    "compute": {
        "template": {
            "outputfields": [],
            "filter": "loanAmount IS NOT NULL"
        }
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.ldrln",
        "namespace": "USER"
    },
    "metadata": {
        "name": "nonulla",
        "namespace": "USER",
        "description": "nonulla",
        "tags": ["nonulla"]
    }
}
