=== isc-rsingh/pipeclient/data/schema/task.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://intersystems.com/schemas/task",
    "title": "Task",
    "description": "A data processing job",
    "type": "object",
    "properties": {
        "taskid": {
            "description": "The unique identifier for a task",
            "type": "string"
        },
        "pipelineids": {
            "description": "IDs of all pipelines that contain this task",
            "type": "array", 
            "items": {
                "type": "string"
            }
        },
        "type": {
            "description": "The type of task (e.g. 'table, recipe, AWS RDS ingest, aggregate, join, etc.')",
            "type": "string"
        },
        "source": {
            "description": "The source data for the task",
            "type": "object",
            "properties": {
                "type": {
                    "description": "The type of data source (internal means IRIS)",
                    "type": "string"
                },
                "tasks": {
                    "description": "The tasks that this task depends upon, identified by their unique identifier",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["type"]
        },
        "compute": {
            "description": "Description of the computation this task will do",
            "type": "object",
            "properties": {
                "template": {
                    "description": "Signals this computation uses a structured format which is good for UIs",
                    "type": "object"
                }
            }
        },
        "sink": {
            "description": "The output data set for the task",
            "type": "object",
            "properties": {
                "type": {
                    "description": "The type of data sink (internal means IRIS)",
                    "type": "string"
                },
                "name": {
                    "description": "The (view or table) name of the data sink. In the case of a recipe, the task ID that represents the recipe's final output",
                    "type": "string"
                },
                "properties": {
                    "description": "Field names of the data sink",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "namespace": {
                    "description": "The namespace of the data sink",
                    "type": "string"
                }
            },
            "required": ["type", "name"]
        },
        "metadata": {
            "description": "Useful information for a catalog",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the task",
                    "type": "string"
                },
                "description": {
                    "description": "Description of the task",
                    "type": "string"
                },
                "autodescription": {
                    "description": "Description of the task as generated by code",
                    "type": "string"
                }, 
                "creator": {
                    "description": "User who created the task",
                    "type": "string"
                },
                "created": {
                    "description": "Date and time the task was created",
                    "type": "string"
                },
                "modified": {
                    "description": "Date and time the task was last updated",
                    "type": "string"
                }, 
                "lastrun": {
                    "description": "Date and time the task was last run",
                    "type": "string"
                },
                "publish": {
                    "description": "Whether this task should appear in the catalog",
                    "type": "boolean"
                },
                "required": ["name", "creator", "created"]
            }
        }
    },
    "required": ["taskid", "type", "source", "sink", "metadata"]
}

=== isc-rsingh/pipeclient/data/samples/tasks/3_task-groupby.json
{
    "taskid": "EC04AD10-EDAC-11EC-8EF9-F4D488652FDC",
    "pipelineids": [],
    "type": "rs.pipeline.TaskGroupBy",
    "source": {
        "type": "internal",
        "tasks": ["0CB27280-EDA9-11EC-8EF5-F4D488652FDC"]
    },
    "compute": {
        "template": {
            "groupfields": ["gender"],
            "aggregationfields": [
                {
                    "name": "credit_history",
                    "aggregation": "avg"
                },
                {
                    "name": "dependents",
                    "outputname": "dependents",
                    "aggregation": "sum"
                }
            ]
        }
    },
    "sink": {
        "type": "iris|view",
        "name": "RSPIPELINE.grouped",
        "namespace": "USER"
    },
    "metadata": {
        "creator": "rsingh"
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/1_task-recipe.json
{
    "taskid": "trecipe",
    "pipelineids": ["p1"],
    "type": "rs.pipeline.TaskRecipe",
    "source": {
        "type": "internal",
        "tasks": ["tloans","ttotinc"]
    },
    "sink": {
        "type": "task", 
        "name": "ttotinc"
    },
    "metadata": {"created":"66202,14742.28642","modified":"66202,14742.28642","creator":"UnknownUser"}
}

=== isc-rsingh/pipeclient/data/samples/tasks/pl1-loanslookup.json
{
    "taskid": "loanslookup",
    "pipelineids": ["pl1"],
    "type": "rs.pipeline.TaskPersistent",
    "source": {
        "type": "internal"
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.LOOKUP",
        "namespace": "USER"
    },
    "metadata": {
        "creator": "rsingh"
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/pl3-loans-drop-selfemp-married-gender.json
{
    "taskid": "loans-drop-selfemp-married-gender",
    "pipelineids": ["pl1"],
    "type": "rs.pipeline.TaskSelectColumns",
    "source": {
        "type": "internal",
        "tasks": ["loans-recipe"]
    },
    "compute": {
        "template": {
            "fields": ["Loan_ID","dependents","education","applicantincome","coapplicantincome","loanamount","loan_amount_term","credit_history","property_area","loan_status"]
        }
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.ldsmg",
        "namespace": "USER"
    },
    "metadata": {
        "name": "nonulla",
        "namespace": "USER",
        "description": "nonulla",
        "tags": ["nonulla"]
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/3_task-python.json
{
    "taskid": "asdflj",
    "pipelineids": [],
    "source": {
        "type": "internal",
        "tasks": []
    },
    "type": "rs.pipeline.TaskPython",
    "compute": {
        "template": {
            "operation": "print ('hello world')"
        }
    },
    "sink": {
        "type": "iris|view",
        "name": "RSPIPELINE.nonulla",
        "namespace": "USER"
    },
    "metadata": {}
}

=== isc-rsingh/pipeclient/data/samples/tasks/4_task-filter2.json
{
    "taskid": "tf2",
    "pipelineids": ["ppp1"],
    "type": "rs.pipeline.TaskFilter",
    "source": {
        "type": "internal",
        "tasks": ["tf1"], 
        "tf1": {
            "fields": ["Loan_ID","Gender","Married","Dependents","Education","Self_Employed"]
        }
    },
    "compute": {
        "template": {
            "outputfields": ["Loan_ID","Gender","Married","Dependents","Education"]
        }
    },
    "sink": {
        "type": "iris|view",
        "name": "RSPIPELINE.tf2",
        "namespace": "USER"
    },
    "metadata": {
        "name": "nonulla",
        "namespace": "USER",
        "description": "nonulla",
        "tags": ["nonulla"]
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/4_task-filter3.json
{
    "taskid": "tf3",
    "pipelineids": ["ppp1"],
    "type": "rs.pipeline.TaskFilter",
    "source": {
        "type": "internal",
        "tasks": ["tf2"], 
        "tf2": {
            "fields": ["Loan_ID","Gender","Married","Dependents","Education"]
        }
    },
    "compute": {
        "template": {
            "outputfields": ["Loan_ID","Gender"]
        }
    },
    "sink": {
        "type": "iris|view",
        "name": "RSPIPELINE.tf3",
        "namespace": "USER"
    },
    "metadata": {
        "name": "nonulla",
        "namespace": "USER",
        "description": "nonulla",
        "tags": ["nonulla"]
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/pl1-loans-join.json
{
    "taskid": "loans-join",
    "pipelineids": ["pl1"],
    "type": "rs.pipeline.TaskJoin",
    "source": {
        "type": "internal",
        "tasks": ["loans-totalincome","loanslookup-recipe"]
    },
    "compute": {
        "template": {
            "source": {
                "id": "loans-totalincome",
                "joinfield": "credit_history",
                "copyfields": [
                    {
                        "name": "loan_ID"
                    },
                    {
                        "name": "totalincome"
                    },
                    {
                        "name": "gender"
                    },
                    {
                        "name": "married"
                    },
                    {
                        "name": "dependents"
                    },
                    {
                        "name": "credit_history"
                    }
                ]
            },
            "reference": {
                "id": "loanslookup-recipe",
                "joinfield": "cr_id",
                "copyfields": [ {"name": "label"} ]
            }
        }
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.JOINEDINCOME",
        "namespace": "USER"
    },
    "metadata": {
        "creator": "rsingh", 
        "name": "Join Loans to credit codes"
    }
}
