=== isc-rsingh/pipeclient/data/schema/task.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://intersystems.com/schemas/task",
    "title": "Task",
    "description": "A data processing job",
    "type": "object",
    "properties": {
        "taskid": {
            "description": "The unique identifier for a task",
            "type": "string"
        },
        "pipelineids": {
            "description": "IDs of all pipelines that contain this task",
            "type": "array", 
            "items": {
                "type": "string"
            }
        },
        "type": {
            "description": "The type of task (e.g. 'table, recipe, AWS RDS ingest, aggregate, join, etc.')",
            "type": "string"
        },
        "source": {
            "description": "The source data for the task",
            "type": "object",
            "properties": {
                "type": {
                    "description": "The type of data source (internal means IRIS)",
                    "type": "string"
                },
                "tasks": {
                    "description": "The tasks that this task depends upon, identified by their unique identifier",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["type"]
        },
        "compute": {
            "description": "Description of the computation this task will do",
            "type": "object",
            "properties": {
                "template": {
                    "description": "Signals this computation uses a structured format which is good for UIs",
                    "type": "object"
                }
            }
        },
        "sink": {
            "description": "The output data set for the task",
            "type": "object",
            "properties": {
                "type": {
                    "description": "The type of data sink (internal means IRIS)",
                    "type": "string"
                },
                "name": {
                    "description": "The (view or table) name of the data sink. In the case of a recipe, the task ID that represents the recipe's final output",
                    "type": "string"
                },
                "properties": {
                    "description": "Field names of the data sink",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "namespace": {
                    "description": "The namespace of the data sink",
                    "type": "string"
                }
            },
            "required": ["type", "name"]
        },
        "metadata": {
            "description": "Useful information for a catalog",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the task",
                    "type": "string"
                },
                "description": {
                    "description": "Description of the task",
                    "type": "string"
                },
                "autodescription": {
                    "description": "Description of the task as generated by code",
                    "type": "string"
                }, 
                "creator": {
                    "description": "User who created the task",
                    "type": "string"
                },
                "created": {
                    "description": "Date and time the task was created",
                    "type": "string"
                },
                "modified": {
                    "description": "Date and time the task was last updated",
                    "type": "string"
                }, 
                "lastrun": {
                    "description": "Date and time the task was last run",
                    "type": "string"
                },
                "publish": {
                    "description": "Whether this task should appear in the catalog",
                    "type": "boolean"
                },
                "required": ["name", "creator", "created"]
            }
        }
    },
    "required": ["taskid", "type", "source", "sink", "metadata"]
}

=== isc-rsingh/pipeclient/data/samples/tasks/3_task-filter.json
{
    "taskid": "AAAB9680-B305-11EC-B8AB-8C8590578FB2",
    "pipelineids": ["4F081870-B293-11EC-B818-8C8590578FB2"],
    "type": "rs.pipeline.TaskFilter",
    "source": {
        "type": "internal",
        "tasks": ["FFA3A030-B303-11EC-B8AB-8C8590578FB2"], 
        "FFA3A030-B303-11EC-B8AB-8C8590578FB2": {
            "fields": ["a", "b", "c"]
        }
    },
    "compute": {
        "template": {
            "outputfields": ["b","c"],
            "filter": "a IS NOT NULL AND a > 0"
        }
    },
    "sink": {
        "type": "iris|view",
        "name": "RSPIPELINE.nonulla",
        "namespace": "USER"
    },
    "metadata": {
        "name": "nonulla",
        "namespace": "USER",
        "description": "nonulla",
        "tags": ["nonulla"]
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/0_task-lookuptable.json
{
    "taskid": "tlookup",
    "pipelineids": ["p1"],
    "type": "rs.pipeline.TaskPersistent",
    "source": {
        "type": "internal"
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.LOOKUP",
        "namespace": "USER"
    },
    "metadata": {
        "creator": "rsingh"
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/pl2-loans-join.json
{
    "taskid": "loans-join-bad",
    "pipelineids": ["pl2"],
    "type": "rs.pipeline.TaskJoin",
    "source": {
        "type": "internal",
        "tasks": ["loans-totalincome-bad","loanslookup-recipe"]
    },
    "compute": {
        "template": {
            "source": {
                "id": "loans-totalincome-bad",
                "joinfield": "credit_history",
                "copyfields": [
                    {
                        "name": "loan_ID"
                    },
                    {
                        "name": "totalincome"
                    },
                    {
                        "name": "gender"
                    },
                    {
                        "name": "married"
                    },
                    {
                        "name": "dependents"
                    },
                    {
                        "name": "credit_history"
                    }
                ]
            },
            "reference": {
                "id": "loanslookup-recipe",
                "joinfield": "cr_id",
                "copyfields": [ {"name": "label"} ]
            }
        }
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.JOINEDINCOMEBAD",
        "namespace": "USER"
    },
    "metadata": {
        "creator": "rsingh"
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/pl1-loans-totalincome.json
{
    "taskid": "loans-totalincome",
    "pipelineids": ["pl1"],
    "type": "rs.pipeline.TaskFieldCompute",
    "source": {
        "type": "internal",
        "tasks": ["loans-recipe"]
    },
    "compute": {
        "template": {
            "targetfield": "totalincome",
            "operation": "applicantincome + coapplicantincome",
            "outfields": [{
                    "name": "applicantincome",
                    "alias": "appincome"
                },
                {
                    "name": "coapplicantincome",
                    "alias": "coappincome"
                },
                {
                    "name": "loan_ID"
                },
                {
                    "name": "gender"
                },
                {
                    "name": "married"
                },
                {
                    "name": "dependents"
                },
                {
                    "name": "credit_history"
                }
            ]
        }
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.TOTALINCOME",
        "namespace": "USER"
    },
    "metadata": {
        "created": "1664072110000",
        "modified": "1664072110000",
        "creator": "UnknownUser", 
        "name": "Total Income"
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/2_task-join.json
{
    "taskid": "tjoin",
    "pipelineids": ["p1"],
    "type": "rs.pipeline.TaskJoin",
    "source": {
        "type": "internal",
        "tasks": ["ttotinc", "tlookup"]
    },
    "compute": {
        "template": {
            "source": {
                "id": "ttotinc",
                "joinfield": "credit_history",
                "copyfields": [
                    {
                        "name": "loan_ID"
                    },
                    {
                        "name": "totalincome"
                    },
                    {
                        "name": "gender"
                    },
                    {
                        "name": "married"
                    },
                    {
                        "name": "dependents"
                    },
                    {
                        "name": "credit_history"
                    }
                ]
            },
            "reference": {
                "id": "tlookup",
                "joinfield": "cr_id",
                "copyfields": [ {"name": "label"} ]
            }
        }
    },
    "sink": {
        "type": "iris|table",
        "name": "RSPIPELINE.xyzjoined",
        "namespace": "USER"
    },
    "metadata": {
        "creator": "rsingh"
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/pl2-loans-totalincome.json
{
    "taskid": "loans-totalincome-bad",
    "pipelineids": ["pl2"],
    "type": "rs.pipeline.TaskFieldCompute",
    "source": {
        "type": "internal",
        "tasks": ["loans-recipe"]
    },
    "compute": {
        "template": {
            "targetfield": "totalincome",
            "operation": "applicantincome + co-applicantincome",
            "outfields": [{
                    "name": "applicantincome",
                    "alias": "appincome"
                },
                {
                    "name": "coapplicantincome",
                    "alias": "coappincome"
                },
                {
                    "name": "loan_ID"
                },
                {
                    "name": "gender"
                },
                {
                    "name": "married"
                },
                {
                    "name": "dependents"
                },
                {
                    "name": "credit_history"
                }
            ]
        }
    },
    "sink": {
        "type": "iris|table",
        "name": "PIPE.TOTALINCOMEBAD",
        "namespace": "USER"
    },
    "metadata": {
        "created": "1664072110000",
        "modified": "1664072110000",
        "creator": "UnknownUser"
    }
}

=== isc-rsingh/pipeclient/data/samples/tasks/1_task-totalincome.json
{
    "taskid": "43443343443443",
    "pipelineids": ["p1","FECA6560-ED26-11EC-8DAF-F4D488652FDC"],
    "type": "rs.pipeline.TaskFieldCompute",
    "source": {
        "type": "internal",
        "tasks": ["85D0E4D0-ED27-11EC-8DAE-F4D488652FDC"]
    },
    "compute": {
        "template": { 
            "targetfield": "totalincome",
            "fields": ["applicantincome","coapplicantincome", "loan_ID", "gender", "married", "dependents", "credit_history"],
            "operation": "applicantincome + coapplicantincome"
        }
    },
    "sink": {
        "type": "iris|view",
        "name": "RSPIPELINE.xyztotinc",
        "namespace": "USER"
    },
    "metadata": {"created":"66202,14742.28642","modified":"66202,14742.28642","creator":"UnknownUser"}
}

=== isc-rsingh/pipeclient/data/samples/tasks/3_task-sqlselect.json
{
    "taskid": "asdflj",
    "pipelineids": [],
    "source": {
        "type": "internal",
        "tasks": []
    },
    "type": "rs.pipeline.TaskSQLSelect",
    "compute": {
        "template": {
            "sql": "SELECT * FROM SAMPLETABLE WHERE a IS NOT NULL AND a > 0"
        }
    },
    "sink": {
        "type": "iris|view",
        "name": "RSPIPELINE.nonulla",
        "namespace": "USER"
    },
    "metadata": {}
}
